import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import type { InitConfig } from './init-config';
import type { ProjectPreflightResult } from './preflight';
import type { ProviderArtifacts } from './provider-install';

export type InstallFileChange = {
  path: string;
  action: 'create' | 'update';
  before: string | null;
  after: string;
};

export type InstallPlan = {
  root: string;
  dependencies: Record<string, string>;
  changes: InstallFileChange[];
  summary: string[];
};

const GENERATED_HEADER = '// Generated by @designfever/web-review-kit. Edit through init or remove this file.';

async function readOptional(path: string) {
  try {
    return await readFile(path, 'utf8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw error;
  }
}

function addGeneratedFile(
  changes: InstallFileChange[],
  path: string,
  before: string | null,
  after: string
) {
  if (before === after) return;
  if (before !== null && !before.startsWith(GENERATED_HEADER)) {
    throw new Error(`INSTALL_FILE_CONFLICT: ${path} exists and is not installer-owned.`);
  }
  changes.push({ path, action: before === null ? 'create' : 'update', before, after });
}

function renderReviewConfig(config: InitConfig, provider?: ProviderArtifacts) {
  if (config.reviewStorage === 'custom') {
    if (!provider) {
      throw new Error('INSTALL_PROFILE_REQUIRED: custom review storage needs provider artifacts.');
    }
    return `${GENERATED_HEADER}\n${provider.source}\nexport const reviewAdapters = [providerCapabilities.review];\n${
      config.figmaImageStore === 'custom'
        ? 'export const figmaImageStore = providerCapabilities.figma;\n'
        : ''
    }`;
  }

  const figmaImport =
    config.figmaImageStore === 'local' ? ', createReviewFigmaImageStoreClient' : '';
  return `${GENERATED_HEADER}
import { localAdapter${figmaImport} } from '@designfever/web-review-kit';

export const reviewAdapters = {
  local: localAdapter({ storageKey: ${JSON.stringify(`${config.projectId}-review-items`)} }),
};
${
  config.figmaImageStore === 'local'
    ? '\nexport const figmaImageStore = createReviewFigmaImageStoreClient();\n'
    : ''
}`;
}

function renderReviewEntry(config: InitConfig) {
  const usesFigma = config.figmaImageStore !== 'none';
  return `${GENERATED_HEADER}
import { createReviewPagesFromGlob, mountReviewShell } from '@designfever/web-review-kit/react-shell';
import { reviewAdapters${usesFigma ? ', figmaImageStore' : ''} } from './review.config';

const projectId = import.meta.env.VITE_REVIEW_PROJECT_ID || ${JSON.stringify(config.projectId)};
const pages = createReviewPagesFromGlob(import.meta.glob('/src/**/*.{jsx,tsx}'), {
  exclude: (href) => href === '/review/',
});

mountReviewShell({
  projectId,
  pages,
  adapters: reviewAdapters,
  ${usesFigma ? 'figmaImages: { store: figmaImageStore },\n  ' : ''}reviewPathPrefix: '/review',
});
`;
}

function renderReviewHtml() {
  return `<!-- Generated by @designfever/web-review-kit. -->
<div id="root"></div>
<script type="module" src="/src/review/index.tsx"></script>
`;
}

function patchEnvExample(before: string | null, entries: string[]) {
  const lines = (before ?? '').split(/\r?\n/);
  let after = before ?? '';
  for (const entry of entries.filter(Boolean)) {
    const separator = entry.indexOf('=');
    if (separator < 1) throw new Error(`INSTALL_ENV_CONFLICT: invalid env entry ${entry}.`);
    const prefix = `${entry.slice(0, separator)}=`;
    const matches = lines.filter((line) => line.startsWith(prefix));
    if (matches.length > 1) {
      throw new Error(`INSTALL_ENV_CONFLICT: duplicate ${prefix.slice(0, -1)} entries.`);
    }
    if (matches.length === 0) {
      after = `${after}${after && !after.endsWith('\n') ? '\n' : ''}${entry}\n`;
      lines.push(entry);
    }
  }
  return after;
}

function patchViteConfig(before: string, config: InitConfig) {
  const requested = [
    ...(config.sourceLocator ? ['reviewSourceLocator()'] : []),
    ...(config.figmaImageStore === 'local'
      ? [`reviewFigmaImageStore({ projectId: ${JSON.stringify(config.projectId)} })`]
      : []),
  ];
  const missing = requested.filter((call) => !before.includes(call.slice(0, call.indexOf('('))));
  if (!missing.length) return before;
  if (!/defineConfig\s*\(/.test(before) || !/plugins\s*:\s*\[/.test(before)) {
    throw new Error('INSTALL_VITE_CONFLICT: expected defineConfig with a plugins array.');
  }

  const names = [
    ...(config.sourceLocator ? ['reviewSourceLocator'] : []),
    ...(config.figmaImageStore === 'local' ? ['reviewFigmaImageStore'] : []),
  ];
  let after = before;
  if (!after.includes("@designfever/web-review-kit/vite")) {
    after = `import { ${names.join(', ')} } from '@designfever/web-review-kit/vite';\n${after}`;
  }
  return after.replace(
    /plugins\s*:\s*\[/,
    (match) => `${match}\n    ${missing.join(',\n    ')},`
  );
}

export async function createInstallPlan(input: {
  root: string;
  config: InitConfig;
  preflight: ProjectPreflightResult;
  provider?: ProviderArtifacts;
  packageVersion?: string;
}): Promise<InstallPlan> {
  const { root, config, preflight, provider } = input;
  if (preflight.support === 'blocked') {
    throw new Error('INSTALL_PREFLIGHT_BLOCKED: resolve blocking diagnostics before generation.');
  }
  const needsVitePatch = config.sourceLocator || config.figmaImageStore === 'local';
  if (needsVitePatch && preflight.files.viteConfigs.length !== 1) {
    throw new Error('INSTALL_VITE_CONFLICT: exactly one Vite config is required for plugin patching.');
  }
  if ((config.reviewStorage === 'custom' || config.figmaImageStore === 'custom') && !provider) {
    throw new Error('INSTALL_PROFILE_REQUIRED: custom capabilities need provider artifacts.');
  }

  const dependencies = {
    '@designfever/web-review-kit': input.packageVersion ?? '^0.9.0',
    ...(provider?.dependencies ?? {}),
  };
  const changes: InstallFileChange[] = [];
  const generated = [
    ['src/review/review.config.ts', renderReviewConfig(config, provider)],
    ['src/review/index.tsx', renderReviewEntry(config)],
    ['review/index.html', renderReviewHtml()],
  ] as const;
  for (const [path, content] of generated) {
    addGeneratedFile(changes, path, await readOptional(join(root, path)), content);
  }

  const envPath = '.env.example';
  const envBefore = await readOptional(join(root, envPath));
  const envEntries = [
    `VITE_REVIEW_PROJECT_ID=${config.projectId}`,
    ...(provider?.envExample.trim().split(/\r?\n/) ?? []),
  ];
  const envAfter = patchEnvExample(envBefore, envEntries);
  if (envBefore !== envAfter) {
    changes.push({
      path: envPath,
      action: envBefore === null ? 'create' : 'update',
      before: envBefore,
      after: envAfter,
    });
  }

  if ((await readOptional(join(root, 'package.json'))) === null) {
    throw new Error('INSTALL_PACKAGE_CONFLICT: package.json is missing.');
  }

  if (needsVitePatch) {
    const vitePath = preflight.files.viteConfigs[0];
    const viteBefore = await readOptional(join(root, vitePath));
    if (viteBefore === null) {
      throw new Error('INSTALL_VITE_CONFLICT: Vite config disappeared during planning.');
    }
    const viteAfter = patchViteConfig(viteBefore, config);
    if (viteBefore !== viteAfter) {
      changes.push({ path: vitePath, action: 'update', before: viteBefore, after: viteAfter });
    }
  }

  changes.sort((a, b) => a.path.localeCompare(b.path));
  return {
    root,
    dependencies,
    changes,
    summary: changes.map((change) => `${change.action.toUpperCase()} ${change.path}`),
  };
}

export async function applyInstallPlan(plan: InstallPlan) {
  for (const change of plan.changes) {
    const current = await readOptional(join(plan.root, change.path));
    if (current !== change.before) {
      throw new Error(`INSTALL_STALE_PLAN: ${change.path} changed after preview; no files were written.`);
    }
  }
  for (const change of plan.changes) {
    const target = join(plan.root, change.path);
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, change.after);
  }
}

export function formatInstallPlan(plan: InstallPlan) {
  if (!plan.changes.length) return 'No changes required.';
  return plan.changes
    .map((change) => {
      const before = change.before ?? '';
      return [
        `--- ${change.action === 'create' ? '/dev/null' : change.path}`,
        `+++ ${change.path}`,
        ...before.split('\n').map((line) => `-${line}`),
        ...change.after.split('\n').map((line) => `+${line}`),
      ].join('\n');
    })
    .join('\n');
}
