import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import type { InitConfig } from './init-config';
import type { ProjectPreflightResult } from './preflight';

export type InstallFileChange = {
  path: string;
  action: 'create' | 'update';
  before: string | null;
  after: string;
};

export type InstallPlan = {
  root: string;
  dependencies: Record<string, string>;
  changes: InstallFileChange[];
  summary: string[];
};

const GENERATED_HEADER = '// Generated by @designfever/web-review-kit. Edit through init or remove this file.';
const DF_CONFIG_PATH = 'df.ts';

async function readOptional(path: string) {
  try {
    return await readFile(path, 'utf8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw error;
  }
}

function addGeneratedFile(
  changes: InstallFileChange[],
  path: string,
  before: string | null,
  after: string
) {
  if (before === after) return;
  if (before !== null && !before.startsWith(GENERATED_HEADER)) {
    throw new Error(`INSTALL_FILE_CONFLICT: ${path} exists and is not installer-owned.`);
  }
  changes.push({ path, action: before === null ? 'create' : 'update', before, after });
}

function renderDfConfig(config: InitConfig) {
  return `${GENERATED_HEADER}
// Public project identifier. Commit this file to Git.
export const REVIEW_PROJECT_ID = ${JSON.stringify(config.projectId)};
`;
}

export async function createInstallPlan(input: {
  root: string;
  config: InitConfig;
  preflight: ProjectPreflightResult;
  packageVersion?: string;
}): Promise<InstallPlan> {
  const { root, config, preflight } = input;
  if (preflight.support === 'blocked') {
    throw new Error('INSTALL_PREFLIGHT_BLOCKED: resolve blocking diagnostics before generation.');
  }

  const dependencies = {
    '@designfever/web-review-kit': input.packageVersion ?? '^0.10.0',
  };
  const changes: InstallFileChange[] = [];
  const generated = [[DF_CONFIG_PATH, renderDfConfig(config)]] as const;
  for (const [path, content] of generated) {
    addGeneratedFile(changes, path, await readOptional(join(root, path)), content);
  }

  if ((await readOptional(join(root, 'package.json'))) === null) {
    throw new Error('INSTALL_PACKAGE_CONFLICT: package.json is missing.');
  }

  changes.sort((a, b) => a.path.localeCompare(b.path));
  return {
    root,
    dependencies,
    changes,
    summary: changes.map((change) => `${change.action.toUpperCase()} ${change.path}`),
  };
}

export async function applyInstallPlan(plan: InstallPlan) {
  for (const change of plan.changes) {
    const current = await readOptional(join(plan.root, change.path));
    if (current !== change.before) {
      throw new Error(`INSTALL_STALE_PLAN: ${change.path} changed after preview; no files were written.`);
    }
  }
  for (const change of plan.changes) {
    const target = join(plan.root, change.path);
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, change.after);
  }
}

export function formatInstallPlan(plan: InstallPlan) {
  if (!plan.changes.length) return 'No changes required.';
  return plan.changes
    .map((change) => {
      const before = change.before ?? '';
      return [
        `--- ${change.action === 'create' ? '/dev/null' : change.path}`,
        `+++ ${change.path}`,
        ...before.split('\n').map((line) => `-${line}`),
        ...change.after.split('\n').map((line) => `+${line}`),
      ].join('\n');
    })
    .join('\n');
}
